--удалить статью
create or replace procedure delArticle(art_id in number) is 
begin
delete operations where article_id=art_id;
delete articles where id=art_id;
end delArticle;

--Сформировать баланс
create or replace procedure createBalance(begin_date in timestamp,end_date in timestamp) is 
ret_id NUMBER;
begin
insert into balance(create_date, debit,credit,amount) values(
end_date,
(select sum(debit) from operations where create_date between begin_date and end_date),
(select sum(credit) from operations where create_date between begin_date and end_date),
(select sum(debit-credit) from operations where create_date between begin_date and end_date))
returning id into ret_id;
update operations set balance_id=ret_id where create_date between begin_date and end_date;
end createBalance; 

--Удалить баланс
create or replace procedure deleteBalance(bal_id in number) is 
ret_id NUMBER;
begin
update operations set balance_id=null where balance_id=bal_id;
delete balance where id=bal_id;
end deleteBalance; 

--Создание таблицы пользователей
CREATE TABLE users
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50 BYTE),
    password VARCHAR2(50 BYTE)
    
);

--Вставка в таблицу пользователей
declare
pass VARCHAR2(50 BYTE);
begin
select DBMS_CRYPTO.HASH(rawtohex('foo') ,2) as md5 into pass from dual;
insert into users(name, password) values('user', pass);
end;

--Динамика изменения расходов и доходов за произвольный период времени и с произвольным набором анализируемых статей. 


--Процентное соотношение финансовых потоков по статьям. 
Это курсор

--Графическое отображение чистой прибыли бюджета от времени
select debit,create_date from balance
